package threeaddress;

/**
 * TempVar.java
 * 
 * @version 1.0
 * 
 * @author Brendan Donohoe
 *
 * Variable class for a variable which was generated by the compiler - rather
 * than the user.
 */
public class TempVar extends Var
{
  public TempVar(int varNum, int size, int align, int offset)
  {
    this.varNum = varNum;
    this.size = size;
    this.align = align;
    this.offset = offset;
  }
  
  public boolean isTemp()
  {
    return true;
  }
  
  public String toString()
  {
    return "t" + varNum /*+ " (offset: " + offset + ")"*/;
  }
}